#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Usage: chrome path_to_resource"
    exit 1
fi
file=$(wslpath -w "$1")
chrome_path="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
"$chrome_path" "$file"